config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :posts, only: [:index, :create, :destroy, :show, :new, :edit] do
        resources :comments, only: [:index, :new, :create]
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :destroy]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :groups, only: [:index, :show, :create]
    end
  end



  namespace :api do
    namespace :v1 do
      resources :messages, only: [:create, :show]
      resources :users, only: [:index]
    end
  end

  resources :users, only: [:search] do
    get 'search', on: :collection
  end

  resources :users, only: [:index, :show, :create, :destroy]
  resources :posts, only: [:new, :create, :index, :show]
  resources :groups, only: [:index, :show, :create, :detroy]

  devise_scope :user do
    get "users/sign_out" => "devise/sessions#destroy"
  end


  get "/groups/:id/chats", to: "homes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :text, presence: true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to  :follower, class_name: "User"
  belongs_to  :followed, class_name: "User"

  validates_uniqueness_of :follower, scope: :followed
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :usergroups
  has_many :users, through: :usergroups

  belongs_to :chat
  validates :name ,presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :user

end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  mount_uploader :post_photo, PostPhotoUploader

  validates :body ,presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :messages

  has_many :usergroups
  has_many :groups, through: :usergroups

  has_many :follower_follows, class_name: "Follow", foreign_key: :follower_id
  has_many :followeds, through: :follower_follows, source: :followed

  has_many :followed_follows, class_name: "Follow", foreign_key: :followed_id
  has_many :followers, through: :followed_follows, source: :follower

  validates_presence_of :first_name, :last_name

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/usergroup.rb
class Usergroup < ApplicationRecord
  belongs_to :user
  belongs_to :group

end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
  def index
    render json: Post.find(params[:post_id]).comments
  end

  def create
    comment = Comment.new(comment_params)
    if comment.save
      render json: comment
    else
      render json: { error: post.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.permit(:text, :post_id)
  end
end

app/controllers/api/v1/groups_controller.rb
class Api::V1::GroupsController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
	before_action :authenticate_user!

  def index
    render json: Group.all
  end

  def show
    group = Group.find(params[:id])
    if Group.find(params[:id]).users.include?(current_user)
      render json: group
    else
      render json: "You are not authorized to view this chat."
    end
  end

	def create
    chatroom = Chat.create()
    group = Group.new(group_params)
		group.chat = chatroom
		if group.save
			Usergroup.create(group_id: group.id, user_id: current_user.id)
      Usergroup.create(group_id: group.id, user_id: params[:selected_follower_id])
			render json: {group: group}
		else
			render json: {error: review.errors.full_messages.join(', ') }, status: :unprocessable_entity
		end
	end

  private
  def group_params
    params.permit(:name)
  end

  def authorize_user
    if !user_signed_in?
      raise ActionController::RoutingError.new("User is not signed in")
    end
  end

end

app/controllers/api/v1/messages_controller.rb
class Api::V1::MessagesController < ApplicationController
	protect_from_forgery unless: -> { request.format.json? }
	before_action :authenticate_user!, except: [:show]

  def show
    message = Chat.find(params[:id]).messages
    render json: message
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
  def index
    render json: Post.all
  end

  def show
    render json: Post.find(params[:id])
  end

  def create
    post = Post.new(post_params)

    if post.save
      render json: post
    else
      render json: { error: post.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.permit(:body, :post_photo)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
	protect_from_forgery unless: -> { request.format.json? }
	before_action :authenticate_user!

	def index
		render json: {users: User.all, current_user_id: current_user.id}
	end

	def show
		render json: User.find(params[:id])
	end

	def create
		follow = Follow.new
		follow.followed = User.find(followed_params)
		follow.follower = current_user
		if follow.followed != follow.follower
			follow.save
			user = User.find(followed_params)
			render json: {followed: user.followeds, followers: user.followers}
		end
	end

	def search
		query = "%#{params[:query]}%"
		user = User.where('first_name ilike ? or last_name ilike ? or email ilike ?', query, query, query)
	end

	def destroy
		follow = Follow.find_by(follower: current_user, followed: User.find(delete_params))
		follow.destroy
    group = Group.find(delete_params)
		user = User.find(delete_params)
		render json: {followed: user.followeds, followers: user.followers}
	end

	private
	def serialize_array(data, serializer)
		ActiveModel::Serializer::CollectionSerializer.new(data, each_serializer: serializer)
	end

	def followed_params
		params.require(:followedId)
	end

	def delete_params
		params.require(:id)
	end

	def authorize_user
		if !user_signed_in?
			raise ActionController::RoutingError.new("User is not signed in")
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

 # Prevent CSRF attacks by raising an exception.

 protect_from_forgery unless: -> { request.format.json? }

 before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
 end

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def show
		if Group.find(params[:id]).users.include?(current_user)
      Group.find(params[:id])
    else
      flash[:notice] = "You are not part of this group."
      redirect_to :controller=>'users', :action=> 'show', :id => current_user.id
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    flash[:notice] = "Successfully deleted group!"
    redirect_to user_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
  end
  
  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
		@users = User.find(params[:id])
  end

  def search
    query = "%#{params[:query]}%"
    @users = User.where('first_name ilike ? or last_name ilike ? or email ilike ?', query, query, query)
  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "Successfully deleted user!"
    redirect_to users_path
  end

  def make_admin
    @user = User.find(params[:id])
    @user.update_attribute :role, "admin"
    flash[:notice] = "Successfully made user admin!"
    redirect_to users_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comment/new.html.erb
<div id='app'></div>

app/views/comment/show.html.erb
<div id='app'></div>

app/views/groups/index.html.erb
<div id="app"> </div>

app/views/groups/show.html.erb
<div id="app"> </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facepage</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= javascript_include_tag "vendor/modernizr" %>

  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar nav-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Facepage</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right small-12 medium-12 columns">
        <li>
        <%= form_tag(search_users_path, method: :get) do %>
          <li class="top-bar">
              <%= text_field_tag 'query', params[:query], placeholder: 'Find a user' %>
            </li>
            <li>
              <%= submit_tag 'Search', :class => 'search' %>
          </li>
        <%- end -%>
      </li>
        <%- if current_user -%>
          <li class="top-bar nav-bar"><%= link_to "Profile", current_user %></li>
          <li class="top-bar nav-bar"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>

          <li class="top-bar nav-bar"><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li class="top-bar nav-bar"><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>

  <%- if Rails.env.development? || Rails.env.test? -%>
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>

  <%= yield :extra_footer %>
</body>
</html>

app/views/posts/index.html.erb
<div id="app"></div>

app/views/posts/new.html.erb
<div id="app"></div>

app/views/posts/show.html.erb
<div id="app"></div>

app/views/users/search.html.erb
<div class="grid-x">
  <div class="cell small-10 small-offset-1">
    <div class="callout tile">
      <h1 class="text-center">Search Results</h1>
      <br />
      <% if @users.empty? %>
        <p>No results found.</p>
      <% else %>
      <p><%= "#{@users.count} result(s) found." %></p>
      <ul class="unstyled">
        <% @users.each do |user| %>
          <li>
            <a href="/users/<%=user.id%>"> <%=user.first_name + " " + user.last_name%> </a>
          </li>
        <% end %>
      </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div id="app"> </div>